// Generated by CoffeeScript 2.3.0
var buble, log, path;

path = require('path');

log = require('lodge');

buble = require('@cush/buble');

buble.parse = require('acorn').parse;

module.exports = function() {
  var transforms;
  transforms = Object.assign({
    modules: false
  }, this.get('buble.transforms'));
  return this.transform('.js', (asset) => {
    return buble.transform(asset.content, {
      includeContent: false,
      objectAssign: 'Object.assign',
      transforms: transforms,
      source: this.relative(asset.path)
    });
  });
};
